name: dart_meteor
description: This library make connection between meteor backend and flutter app easily. Design to work seamlessly with StreamBuilder and FutureBuilder.
version: 1.1.2
homepage: https://github.com/tanutapi/dart_meteor

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  rxdart: ^0.26.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
